// client/src/utils/recipeHistory.js
// Client-side storage of viewed and generated recipes so they persist across routes and refreshes
const STORAGE_KEY = 'smartai_recipe_history';
const VIEWED_KEY = 'smartai_viewed_recipes';
const MAX_ENTRIES = 40;

export function getRecipeHistory() {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    const parsed = raw ? JSON.parse(raw) : [];
    return Array.isArray(parsed) ? parsed : [];
  } catch (e) {
    return [];
  }
}

export function addRecipeHistoryEntry({ preferences, recipes }) {
  try {
    const history = getRecipeHistory();
    const entry = {
      id: `${Date.now()}`,
      createdAt: new Date().toISOString(),
      preferences,
      resultCount: Array.isArray(recipes) ? recipes.length : 0,
      recipes: Array.isArray(recipes) ? recipes : [],
    };
    const next = [entry, ...history].slice(0, MAX_ENTRIES);
    localStorage.setItem(STORAGE_KEY, JSON.stringify(next));

    // Also persist all recipes individually into viewed recipes
    if (Array.isArray(recipes)) {
      recipes.forEach((r) => saveViewedRecipe(r));
    }

    return entry;
  } catch (e) {
    return null;
  }
}

// Stores an individual recipe when viewed or generated by AI
export function saveViewedRecipe(recipe) {
  if (!recipe || (!recipe.id && !recipe.title)) return;
  try {
    const current = getViewedRecipes();
    // Check if recipe already exists
    const existsIdx = current.findIndex(
      (r) =>
        (recipe.id && (r.id === recipe.id || r._id === recipe.id)) ||
        (recipe.title && r.title?.toLowerCase() === recipe.title?.toLowerCase())
    );

    const enriched = {
      ...recipe,
      viewedAt: new Date().toISOString(),
    };

    let next;
    if (existsIdx >= 0) {
      // Move to top with updated viewedAt
      next = [enriched, ...current.filter((_, i) => i !== existsIdx)];
    } else {
      next = [enriched, ...current];
    }

    localStorage.setItem(VIEWED_KEY, JSON.stringify(next.slice(0, MAX_ENTRIES)));
    return enriched;
  } catch (e) {
    console.warn('Failed to save viewed recipe:', e);
  }
}

export function getViewedRecipes() {
  try {
    const raw = localStorage.getItem(VIEWED_KEY);
    const parsed = raw ? JSON.parse(raw) : [];
    return Array.isArray(parsed) ? parsed : [];
  } catch (e) {
    return [];
  }
}

export function clearViewedRecipes() {
  try {
    localStorage.removeItem(VIEWED_KEY);
  } catch (e) {}
}

export function clearRecipeHistory() {
  try {
    localStorage.removeItem(STORAGE_KEY);
    localStorage.removeItem(VIEWED_KEY);
  } catch (e) {}
}
